### ISSUE TITLE
Error / Loading

### ISSUE THREAD

**Issue by stefkeexyz** [ItsPi3141/discord-fake-avatar-decorations#1]
![image](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/156558120/1717c8c3-5b7b-4be9-8b92-44f4da063184)
![image](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/156558120/58e2d11e-ab3c-4e7b-aa55-dde8d905237a)

**Comment by ItsPi3141** [comment]
I am working on fixing this 🙂

**Comment by kabirshivanikumar** [comment]
Also my picture shows a question mark in the photo preview and then it gives that error

**Comment by ItsPi3141** [comment]
I have fixed the issue. Try clearing cache if it does not work. If the issue still persists, let me know. A screenshot of the console would also be helpful.

**Comment by stefkeexyz** [comment]
> I have fixed the issue. Try clearing cache if it does not work. If the issue still persists, let me know. A screenshot of the console would also be helpful.
> 
> @kabirshivanikumar @stefkeexyz

![image](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/156558120/489b5e3b-0be8-4952-b4f9-81a69dbbe482)

**Comment by ItsPi3141** [comment]
What file type are you trying to upload?

**Comment by kabirshivanikumar** [comment]
> What file type are you trying to upload?

JPG, this file that I am attaching right now.
![Photoroom_20240607_103524](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/86461562/9c0f11a4-497e-4213-852c-c3bfd327eff8)

**Comment by kabirshivanikumar** [comment]
Same error as for @stefkeexyz . Only loading and then 'Failed to generate image' if i click save image

**Comment by ItsPi3141** [comment]
> JPG, this file that I am attaching right now. 

> Same error as for @stefkeexyz . Only loading and then 'Failed to generate image' if i click save image

Hello @kabirshivanikumar and @stefkeexyz, the issue was caused by the code not detecting JPEG file formats correctly. I have fixed the issue. Please let me know if you encounter any other difficulties. 
![image](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/90981829/a213cdca-4534-48c5-b0f7-912386bca6ea)

**Comment by ItsPi3141** [comment]
Closed due to inactivity
