### ISSUE TITLE
add this new animation                  https://cdn.discordapp.com/avatar-decoration-presets/a_90e0dce3cc48c4a9607b6d41209c737e.png?size=300&passthrough=true

### ISSUE THREAD

**Issue by nshywq** [ItsPi3141/discord-fake-avatar-decorations#12]
https://cdn.discordapp.com/avatar-decoration-presets/a_90e0dce3cc48c4a9607b6d41209c737e.png?size=300&passthrough=true
add this animation

**Comment by ItsPi3141** [comment]
Thanks! I've just added it in db95b7192a156737d06e3264053145400a92f9e7 😁
