### ISSUE TITLE
The hot shot effect is broken

### ISSUE THREAD

**Issue by potato7YT** [ItsPi3141/discord-fake-avatar-decorations#2]
![Screenshot_2024-06-20-23-17-32-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/8fcde087-a4a9-4dae-a627-5c2e9c98a925)
No matter what you do it will do this 
Can you create a discord server 🌹
I have an some ideas it'll be incredible if you implement it
Like for example 
A advanced mode that you can change the size of the effect and position 
And the size of the image
And a custom effects tab

And a banner effects
Like the profile effects but for banners
And also
There's a bug
When  i tried it on gifs the effect was fine but the main gif will not loop
It will play one time and stop

**Comment by potato7YT** [comment]
Oh yeah and i wanted to download the assets to have more freedom and all the effect are png-s non-animated
If you can help I'll be very thankful 😄 
Thanks for the hard work

**Comment by ItsPi3141** [comment]
I've fixed the Hot Shot decoration. It should work now 😁

**Comment by ItsPi3141** [comment]
As for feature suggestions, you can put them in this discussion here: https://github.com/ItsPi3141/discord-fake-avatar-decorations/discussions/4

**Comment by ItsPi3141** [comment]
> There's a bug When i tried it on gifs the effect was fine but the main gif will not loop It will play one time and stop

See #5
