### ISSUE TITLE
Animated profile pictures animate only once

### ISSUE THREAD

**Issue by ItsPi3141** [ItsPi3141/discord-fake-avatar-decorations#5]
See #2

**Comment by potato7YT** [comment]
There's a bug When i tried it on gifs the effect was fine but the main gif will not loop It will play one time and stop

**Comment by potato7YT** [comment]
Original image 
![download_2](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/389f4239-5724-4472-9841-0b2455153e31)
Image with decoration
![discord_fake_avatar_decorations_1719519337436](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/54bda800-c203-4666-bfd0-61a335c4f614)

**Comment by potato7YT** [comment]
@ItsPi3141 when i tried it with longer gif
The was no problem 
I think you should make it chech if the gif length is shorter than the decoration length 
And make it loob probably 
thanks 🤍

**Comment by ItsPi3141** [comment]
If it loops, it will be cut off abruptly when the decoration animation ends. I think it's fine the way it is... what do you think?

**Comment by potato7YT** [comment]
> If it loops, it will be cut off abruptly when the decoration animation ends. I think it's fine the way it is... what do you think?

I think it's better to make the original image loob
Now it feels like it's lagging or glitching or something idk
![__1718924429104](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/0c123194-9708-4686-8652-f46872a8ed3f)

**Comment by ItsPi3141** [comment]
I just fixed it in this commit 0307fc7eeacef03af7ba334b889365f0732598e3

**Comment by ItsPi3141** [comment]
Completed with 2c6a1b416482f67c576dc4b646b0d9cc25c243e1
