### ISSUE TITLE
Snowsgiving effects aren't working properly. 

### ISSUE THREAD

**Issue by potato7YT** [ItsPi3141/discord-fake-avatar-decorations#6]
![Screenshot_2024-06-29-21-09-04-81_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/b9e500c6-0f36-4c8d-a26e-446229505f83)
![Screenshot_2024-06-29-21-08-56-15_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/7e23f422-934f-491e-9402-cb84820df3cc)
![Screenshot_2024-06-29-21-08-23-27_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/3d26deaa-d0e6-4964-be36-5ff6be523687)
![Screenshot_2024-06-29-21-07-21-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ItsPi3141/discord-fake-avatar-decorations/assets/85459992/aec00ef9-8624-4ad4-affc-0880aaa646a5)

The size is wrong 😔 
And thanks for the hard work 😊 
@ItsPi3141

**Comment by ItsPi3141** [comment]
Fixed in 78917eb5b764ef33657720ce2676610d170e3b6a
Thanks for letting me know
